name: GitHub Actions Demo Testing Scraping
run-name: test-run
on: 
  schedule:
    - cron: '*/15 * * * *' # Run every 15 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check job status and environment
        run: |
          echo "Status Checking... "
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Verify repository checkout
        run: |
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."

      - name: List files in the repository before running the script
        run: |
          ls ${{ github.workspace }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Verify Python setup
        run: |
          echo "Python 3.10 has been set up on the runner."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: install playwright browsers
        run: |
          playwright install chromium

      - name: Run the Python script
        run: |
          python index.py

      - name: Commit and push CSV back to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Stage the specific file pattern your script generates
          git add "./result/countries-*-*.txt"
          
          # Commit the file. The '|| echo' prevents the workflow from failing if no new file was generated
          git commit -m "Automated data scrape: added new countries CSV" || echo "No changes to commit"
          
          # Push it back to the main branch
          git push

      - run: echo "🍏 This job's status is ${{ job.status }}."
